### ISSUE TITLE
Mingw-5.1.0 Compilation Error ld `-mbig_obj` not supported

### ISSUE THREAD

**Issue by tilkinsc** [assimp/assimp#2315]
I was trying to build via the Code Blocks mingw, which is packaged with mingw-5.1.0 and ran into an error.

Windows 10
Mingw-5.1.0 (Code Blocks)
CMD, not msys

```
set path=code_blocks_mingw_bin;%path%
pushd assimp-4.1.0
mkdir build
pushd build
cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON ..
mingw32-make -j5
popd
popd
```

make fails because option `-mbig_obj` was not supported. Same script works fine for gcc 7.1

**Comment by tilkinsc** [comment]
The problem with updating it is it ships with Code Blocks.

**Comment by kkulling** [comment]
Ok, then we have to check which mingw-version is currently in use.

**Comment by kimkulling** [comment]
Sorry, you need to update your compiler. Hopefully this documentation can help you with that step: http://wiki.codeblocks.org/index.php/MinGW_installation

**Comment by tilkinsc** [comment]
Rightfully so, I did this and it worked. FWIW I tried to build with gcc 7.1 and linked it with 5.1, the building went okay but had errors due to `Assimp::Importer::Importer undefined reference`

**Comment by kimkulling** [comment]
Ok, back to the keyboards ...

**Comment by kimkulling** [comment]
Have you add the assimp-lib to the list of linked libraries?

**Comment by tilkinsc** [comment]
Yes, as soon as I changed the compiler out, the library would work (with the one that built with -mbig-obj). The problem is probably because mingw-5.1.0 was too old to recognize how to binary was made with -mbig-obj.
