### PR TITLE
Common: Fix GCC error invalid conversion in MINGW.

### PR DESCRIPTION
**Pull request by Biswa96**
Fixes https://github.com/assimp/assimp/issues/3144

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.

**Comment by JLouis-B** [comment]
Hello,
Assimp fail to compile with MinGW 7.3 since this PR :
`assimp-master\code\Common\ZipArchiveIOSystem.cpp|156|error: 'error_file_func' was not declared in this scope|`

**Comment by Biswa96** [comment]
I have compiled assimp in MSYS2/MinGW-w64 toolchain without any issue now. Try to update your MinGW setup or use MSYS2 which provides latest toolchain.

**Comment by Biswa96** [comment]
I have used MSYS2/MinGW-w64 toolchain to compile assimp. The `error_file_func` function pointer present in minizip v1.2 package here https://github.com/nmoinvaz/minizip/blob/1.2/ioapi.h

**Comment by JLouis-B** [comment]
The issue is that ZipArchiveIOSystem.cpp use error_file_func which is defined in minizip 1.2 as you show, but assimp/contrib seems to be based on minizip 1.1 which does not define error_file_func but testerror_file_func

assimp/contrib/unzip+zip should probably be updated
