### PR TITLE
fix compilation with clangcl on windows

### LINKED ISSUE #3565: Compilation error on Clang 12.0.0
**Describe the bug**
Compilation error on Clang 12.0.0:
```
Assimp/include/assimp/TinyFormatter.h:122:20: error: invalid operands to binary expression ('Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char>>::stringstream' (aka 'basic_ostringstream<char, std::char_traits<char>, std::allocator<char>>') and 'const DeadlyImportError')
```
The offending file which includes the formatter is:
```
Assimp/code/PostProcessing/DropFaceNormalsProcess.cpp
```

**To Reproduce**
1. Compile on Windows with Clang 12.0.0.

**Expected behavior**
1. Compilation should have succeeded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 build 20H2

### PR DESCRIPTION
**Pull request by malytomas**
PR with fix as suggested by @KonopaKrzysztof including the comma operator.
fixes #3565

I still get an error with signed/unsigned comparison somewhere inside gtest, but that is for another issue/pr.

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Looks good so far. Thanks for fixing that annoying bug.

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.
