### ISSUE TITLE
MacOSX: undeclared identifier 'AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST'

### ISSUE THREAD

**Issue by jsfrancal** [assimp/assimp#2258]
With the current master compilation fails on my MacOSX machine with the following message:

```
[ 51%] Building CXX object code/CMakeFiles/assimp.dir/SMDLoader.cpp.o
[...]/build/assimp/code/SMDLoader.cpp:126:48: error: use of undeclared identifier 'AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST'
    bLoadAnimationList = pImp->GetPropertyBool(AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST, true);
```

This compilation error doesn't show up on a Linux Ubuntu 16.04 LTS machine and the lib builds fine there. Previous commits of the code, e.g. ef151b46100238dc491b09e0d645973ce1fc8c81, build under MacOSX with no issue.

Looking at the history of SMDLoader.cpp, the issue seems to have been introduced with commit 19521d222b905f7420346133116f84031ab962d0 to 'Issue 1117: Smd load multiple animations'. I haven't figured out why the new #define in include/assimp/config.h.in line 681 isn't seen in SMDLoader.cpp.

**Comment by jsfrancal** [comment]
A clean checkout solves this problem. It seems that I had mistakenly generated a previous build in place instead of a dedicated "build" subdirectory, and that an old "config.h" file was left over in ./include/assimp as a result, with no AI_CONFIG_IMPORT_SMD_LOAD_ANIMATION_LIST macro definition, which was being picked up by the compilation instead of the newer one. The issue can be closed.
