### ISSUE TITLE
python-wrapper stopped working...

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#4208]
thy `PyAssimp` python wrapper in *port/PyAssimp* can no longer open files...

~~~sh
$ cd port/PyAssimp
$ python3 scripts/sample.py ../../test/models/OBJ/box.obj
MODEL:../../test/models/OBJ/box.obj
SCENE:
Traceback (most recent call last):
  File "@PATH@/port/PyAssimp/scripts/sample.py", line 89, in <module>
    main(sys.argv[1])
  File "@PATH@/port/PyAssimp/scripts/sample.py", line 31, in main
    print("  meshes:" + str(len(scene.meshes)))
AttributeError: '_GeneratorContextManager' object has no attribute 'meshes'
~~~

it used to work with assimp-5.0.1

**Comment by kimkulling** [comment]
If I get the linked issue report right this seems to be related. And the other but-report mentioned that the used assimp-version is outdated (version 5.0.0 is in use, 5.1.3 is the latest one).

So my expectation is that with an update to the latest-greatest this issue will vanish.

If this is not the case: please reopen the issue again!

**Comment by umlaeute** [comment]
unfortunately the issue is not resolved.
i still get the `'_GeneratorContextManager' object has no attribute 'meshes'` with assimp-5.1.4.


- a logfile of a failed test-run with assimp-5.1.5 can be found [here](https://salsa.debian.org/debian/assimp/-/jobs/2300007) :boom:  
- an old logfile of a successful test-run with assimp-5.0.1 can be found [here](https://salsa.debian.org/debian/assimp/-/jobs/2037656) :tada: 

(@kimkulling i don't have the supercow powers to re-open the ticket myself)

**Comment by umlaeute** [comment]
sidenote: the issues were not really linked; i just referenced *this* issue to explain that new "minor" releases can introduce regressions...
