### ISSUE TITLE
Bug: Error compiling for android using make_android.bat script

### ISSUE THREAD

**Issue by abenedik** [assimp/assimp#5408]
**Describe the bug**
I get an error when trying to compile Assimp (official 5.3.1 and also the latest version from 2024-01-03) for Android using the make_android.bat script from the scripts\android_crosscompile folder.

I am using the latest Android NDK (26.1.10909125) and cmake on Windows 10.

I am able to compile Assimp for Windows by using the BUILDBINARIES_EXAMPLE.bat scipt.

The following errors are shown during compilation:
```
assimp-5.3.1/contrib/unzip/ioapi.c:129:16: error: call to undeclared
      function 'fopen64'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
        file = FOPEN_FUNC((const char*)filename, mode_fopen);
```

```
assimp-5.3.1/contrib/unzip/ioapi.c:129:14: error: incompatible integer
      to pointer conversion assigning to 'FILE *' (aka 'struct __sFILE *') from 'int' [-Wint-conversion]
        file = FOPEN_FUNC((const char*)filename, mode_fopen);
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

```
assimp-5.3.1/contrib/unzip/ioapi.c:163:21: error: call to undeclared
      function 'ftello64'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
    ret = (ZPOS64_T)FTELLO_FUNC((FILE *)stream);
```

```
assimp-5.3.1/contrib/unzip/ioapi.c:211:8: error: call to undeclared
      function 'fseeko64'; ISO C99 and later do not support implicit function declarations
      [-Wimplicit-function-declaration]
    if(FSEEKO_FUNC((FILE *)stream, (z_off_t)offset, fseek_origin) != 0)
```

Platform:
```
Enter Android platform - Enter to use 21: 21
Enter Android ABI ( armeabi-v7a, arm64-v8a , x86 , x86_64 ) - Enter to use armeabi-v7a : arm64-v8a
Found cmake at "C:\Program Files\CMake\bin\cmake.exe"
Found NDK at "C:\Users\User\AppData\Local\Android\Sdk\ndk\26.1.10909125"
The system cannot find the file specified.
-- The C compiler identification is Clang 17.0.2
-- The CXX compiler identification is Clang 17.0.2
```

**To Reproduce**
Start scripts\android_crosscompile\make_android.bat script

**Platform (please complete the following information):**
 - OS: Windows 10
 - Assimp version: official 5.3.1 and latest (2024-01-03)
 - Android platform: 21
 - Android ABI: armeabi-v7a or arm64-v8a - tried both and the same error occurs

**Comment by nezticle** [comment]
I'm having a similar issue with building on Android when updating the Assimp version of Qt to 5.3.1.  The updated unzip (from zlib/contrib/minizip presumably) has some additional logic regarding the large-file io API (stdio.h stuff), and there is no logic for Android.  If you try and build with a NDK-SDK version < 24 it will break the build since then only "fopen, fseek, ftell" are defined which doesn't work with the logic as is.  

I worked around it with the following:
`
diff --git a/contrib/unzip/ioapi.h b/contrib/unzip/ioapi.h
index ae9ca7e83..38b700f2f 100644
--- a/contrib/unzip/ioapi.h
+++ b/contrib/unzip/ioapi.h
@@ -45,7 +45,7 @@
 #include <stdlib.h>
 #include "zlib.h"

-#if defined(USE_FILE32API)
+#if defined(USE_FILE32API)  || (defined(__ANDROID__) && (__ANDROID_API__ < 24))
 #define fopen64 fopen
 #define ftello64 ftell
 #define fseeko64 fseek
 `
 Which probably will limit the file size that can used (not sure, didn't test, but got mixed messages from the Android docs), but just looking at the code in the latest Android NDK (stdio.h) this is what is needed at least for this combo of build.

**Comment by retifrav** [comment]
Got the same problem with Assimp v5.3.1 not-sure-which-exactly Android NDK/API version (*there is a mix of different buildbots from different projects, or just a mess in other words*). The patch from @nezticle worked out fine, thanks a lot for sharing it!

The only note is that we applied just the `|| (defined(ANDROID)` part, so without API version check, as it's a bit challenging to find out which exact versions have the problem in our messy setup (*as some build agents have been building fine even with unmodified header*), and that seems to have satisfied all of them.

**Comment by tellypresence** [comment]
@abenedik Is this still a problem?

**Comment by tellypresence** [comment]
Closing old build problem report
