### ISSUE TITLE
Compilation error on Clang 12.0.0

### ISSUE THREAD

**Issue by SparkyPotato** [assimp/assimp#3565]
**Describe the bug**
Compilation error on Clang 12.0.0:
```
Assimp/include/assimp/TinyFormatter.h:122:20: error: invalid operands to binary expression ('Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char>>::stringstream' (aka 'basic_ostringstream<char, std::char_traits<char>, std::allocator<char>>') and 'const DeadlyImportError')
```
The offending file which includes the formatter is:
```
Assimp/code/PostProcessing/DropFaceNormalsProcess.cpp
```

**To Reproduce**
1. Compile on Windows with Clang 12.0.0.

**Expected behavior**
1. Compilation should have succeeded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 build 20H2

**Comment by kimkulling** [comment]
Honestly speaking: I do not have a clue. Anyone else?

**Comment by SparkyPotato** [comment]
It could just be an incompatibility with Clang 12 and the MSVC standard library, but I don't think that is the case.
It seems like it's trying to log a `DeadlyImportError` into an output stream.

Here's the entire error:
```
In file included from ../../External/Assimp/code/PostProcessing/DropFaceNormalsProcess.cpp:52:
In file included from ../../External/Assimp/include\assimp/DefaultLogger.hpp:49:
In file included from ../../External/Assimp/include\assimp/Logger.hpp:50:
../../External/Assimp/include\assimp/TinyFormatter.h:122:20: error: invalid operands to binary expression ('Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char>>::stringstream' (aka 'basic_ostringstream<char, std::char_traits<char>, std::allocator<char>>') and 'const DeadlyImportError')
        underlying << s;
        ~~~~~~~~~~ ^  ~
../../External/Assimp/include\assimp/Exceptional.h:65:41: note: in instantiation of function template specialization 'Assimp::Formatter::basic_formatter<char, std::char_traits<char>, std::allocator<char>>::operator<<<DeadlyImportError>' requested here
            DeadlyErrorBase(std::move(f << std::forward<U>(u)), std::forward<T>(args)...) {}
                                        ^
../../External/Assimp/include\assimp/Exceptional.h:77:13: note: in instantiation of function template specialization 'DeadlyErrorBase::DeadlyErrorBase<, DeadlyImportError &>' requested here
            DeadlyErrorBase(Assimp::Formatter::format(), std::forward<T>(args)...) {}
            ^
../../External/Assimp/code/PostProcessing/DropFaceNormalsProcess.cpp:83:15: note: in instantiation of function template specialization 'DeadlyImportError::DeadlyImportError<DeadlyImportError &>' requested here
        throw DeadlyImportError("Post-processing order mismatch: expecting pseudo-indexed (\"verbose\") vertices here");
              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:653:32: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'const char *' for 2nd argument
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr, const char* _Val) { // insert NTBS
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:697:32: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'char' for 2nd argument
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr, char _Ch) { // insert a character
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:733:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'const char *' for 2nd argument
basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>& _Ostr,
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:778:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'char' for 2nd argument
basic_ostream<char, _Traits>& operator<<(
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:895:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'const signed char *' for 2nd argument
basic_ostream<char, _Traits>& operator<<(
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:901:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'signed char' for 2nd argument
basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>& _Ostr, signed char _Ch) { // insert a signed char
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:906:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'const unsigned char *' for 2nd argument
basic_ostream<char, _Traits>& operator<<(
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:912:31: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'unsigned char' for 2nd argument
basic_ostream<char, _Traits>& operator<<(
                              ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:998:32: note: candidate function template not viable: no known conversion from 'const DeadlyImportError' to 'const std::error_code' for 2nd argument
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr,
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:859:32: note: candidate template ignored: deduced conflicting types for parameter '_Elem' ('char' vs. 'DeadlyImportError')
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr, _Elem _Ch) { // insert a character
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\xstring:4724:32: note: candidate template ignored: could not match 'basic_string<type-parameter-0-0, type-parameter-0-1, type-parameter-0-2>' against 'const DeadlyImportError'
basic_ostream<_Elem, _Traits>& operator<<(
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\memory:2077:32: note: candidate template ignored: could not match 'shared_ptr<type-parameter-0-2>' against 'const DeadlyImportError'
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Out, const shared_ptr<_Ty>& _Px) {
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\memory:3718:32: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-2, type-parameter-0-3>' against 'const DeadlyImportError'
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Out, const unique_ptr<_Yty, _Dx>& _Px) {
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:816:32: note: candidate template ignored: could not match 'const _Elem *' against 'DeadlyImportError'
basic_ostream<_Elem, _Traits>& operator<<(basic_ostream<_Elem, _Traits>& _Ostr, const _Elem* _Val) { // insert NTCS
                               ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:970:9: note: candidate template ignored: substitution failure [with _Ostr = std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char>> &, _Ty = DeadlyImportError]: 'type name' declared as a pointer to a reference of type 'std::basic_ostringstream<char, std::char_traits<char>, std::allocator<char>> &'
_Ostr&& operator<<(_Ostr&& _Os, const _Ty& _Val) { // insert to rvalue stream
        ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:183:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'std::basic_ostream<char, char_traits<char>> &(*)(std::basic_ostream<char, char_traits<char>> &) __attribute__((cdecl))' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:188:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'std::basic_ostream<char, std::char_traits<char>>::_Myios &(*)(std::basic_ostream<char, std::char_traits<char>>::_Myios &) __attribute__((cdecl))' (aka 'basic_ios<char, std::char_traits<char>> &(*)(basic_ios<char, std::char_traits<char>> &)') for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(_Myios&(__cdecl* _Pfn)(_Myios&) ) { // call basic_ios manipulator
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:193:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'std::ios_base &(*)(std::ios_base &) __attribute__((cdecl))' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(ios_base&(__cdecl* _Pfn)(ios_base&) ) { // call ios_base manipulator
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:198:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'bool' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(bool _Val) { // insert a boolean
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:216:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'short' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(short _Val) { // insert a short
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:250:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'unsigned short' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(unsigned short _Val) { // insert an unsigned short
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:269:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'int' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(int _Val) { // insert an int
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:295:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'unsigned int' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(unsigned int _Val) { // insert an unsigned int
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:314:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'long' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(long _Val) { // insert a long
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:332:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'unsigned long' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(unsigned long _Val) { // insert an unsigned long
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:350:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'long long' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(long long _Val) { // insert a long long
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:368:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'unsigned long long' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(unsigned long long _Val) { // insert an unsigned long long
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:386:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'float' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(float _Val) { // insert a float
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:404:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'double' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(double _Val) { // insert a double
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:422:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'long double' for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(long double _Val) { // insert a long double
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:440:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'const void *' for 1st argument; take the address of the argument with &
    basic_ostream& __CLR_OR_THIS_CALL operator<<(const void* _Val) { // insert a void pointer
                                      ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.28.29812\include\ostream:465:39: note: candidate function not viable: no known conversion from 'const DeadlyImportError' to 'std::basic_ostream<char, std::char_traits<char>>::_Mysb *' (aka 'basic_streambuf<char, std::char_traits<char>> *') for 1st argument
    basic_ostream& __CLR_OR_THIS_CALL operator<<(_Mysb* _Strbuf) { // insert until end-of-file from a stream buffer
                                      ^
1 error generated.
```

**Comment by kimkulling** [comment]
I am struggling with this as well:

`D:\projects\assimp\code\Common\BaseImporter.cpp(341,15): error : no matching constructor for initialization of 'DeadlyImportError'
3>D:\projects\assimp\include\assimp/Exceptional.h(74,5): message : candidate constructor not viable: no known conversion from 'DeadlyImportError' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(86,5): message : candidate constructor not viable: expects an l-value for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(82,14): message : explicit constructor is not a candidate
3>D:\projects\assimp\code\Common\BaseImporter.cpp(436,19): error : no matching constructor for initialization of 'DeadlyImportError'
3>D:\projects\assimp\include\assimp/Exceptional.h(74,5): message : candidate constructor not viable: no known conversion from 'DeadlyImportError' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(86,5): message : candidate constructor not viable: expects an l-value for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(82,14): message : explicit constructor is not a candidate
3>D:\projects\assimp\code\Common\BaseImporter.cpp(444,19): error : no matching constructor for initialization of 'DeadlyImportError'
3>D:\projects\assimp\include\assimp/Exceptional.h(74,5): message : candidate constructor not viable: no known conversion from 'DeadlyImportError' to 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(86,5): message : candidate constructor not viable: expects an l-value for 1st argument
3>D:\projects\assimp\include\assimp/Exceptional.h(82,14): message : explicit constructor is not a candidate
3>Done building project "assimp.vcxproj" -- FAILED.
4>------ Build started: Project: assimp_cmd, Configuration: Debug x64 ------`

**Comment by KonopaKrzysztof** [comment]
@SparkyPotato @kimkulling

This issue was blocking me so I took some time and I have something that seems to work (well, at least compile).

A. Minimal example 1:

```c++
#include <stdexcept>

struct demo : public std::runtime_error
{
    demo(const char* test) : std::runtime_error(test){};
    demo(demo &) = delete;
};

int main()
{
    throw demo{"test"};
    return 0;
}
```

https://stackoverflow.com/a/58777465  
https://timsong-cpp.github.io/cppwp/n3337/except.throw#5

1. From include/assimp/Exceptional.h you can remove:

```c++
#if defined(_MSC_VER) && defined(__clang__)
    DeadlyImportError(DeadlyImportError& other) = delete;
#endif
```

and:

```c++
#if defined(_MSC_VER) && defined(__clang__)
    DeadlyExportError(DeadlyExportError& other) = delete;
#endif
```

But that still doesn't solve compilation issues.

B: Minimal example 2:

```c++
#include <iostream>
#include <sstream>
#include <stdexcept>

int main()
{
    std::basic_ostringstream<char> test{};
    std::runtime_error err{"Test"};
    //V1
	//test << err;
    //V2
	test << err.what();
    std::cout << test.str();
}
```

V1 won't work but that's basically what's happening later.

2. You can use some old-school SFINAE in include/assimp/TinyFormatter.h:

by replacing this:

```c++
template <typename TToken>
const basic_formatter& operator << (const TToken& s) const {
	underlying << s;
	return *this;
}

template <typename TToken>
basic_formatter& operator << (const TToken& s) {
	underlying << s;
	return *this;
}
```

with this:

```c++
template <typename TToken, typename std::enable_if<!std::is_base_of<std::exception, TToken>::value>::type* = nullptr>
const basic_formatter& operator << (const TToken& s) const {
	underlying << s;
	return *this;
}

template <typename TToken, typename std::enable_if<std::is_base_of<std::exception, TToken>::value>::type* = nullptr>
const basic_formatter& operator << (const TToken& s) const {
	underlying << s.what();
	return *this;
}

template <typename TToken, typename std::enable_if<!std::is_base_of<std::exception, TToken>::value>::type* = nullptr>
basic_formatter& operator << (const TToken& s) {
	underlying << s;
	return *this;
}

template <typename TToken, typename std::enable_if<std::is_base_of<std::exception, TToken>::value>::type* = nullptr>
basic_formatter& operator << (const TToken& s) {
	underlying << s.what();
	return *this;
}
```

Coma operator might be the same but I didn't bother.

3. Same file, add relevant headers:

```c++
#include <exception>
#include <type_traits>
```

Tested on Windows 8.1 x64 from master branch, both Clang 12 official LLVM release from GitHub (GNU-like) and Clang-CL from MSVC 2019 (MSVC-like).

```sh
cmake -B Build-Clang -S . -G "Unix Makefiles" -DASSIMP_BUILD_ASSIMP_TOOLS=False -DASSIMP_BUILD_ZLIB=True -DCMAKE_C_COMPILER="..." -DCMAKE_CXX_COMPILER="..."

cmake -B Build-ClangCL -S . -G "Visual Studio 16 2019" -A x64 -T ClangCL -DASSIMP_BUILD_ASSIMP_TOOLS=False -DASSIMP_BUILD_ZLIB=True -DCMAKE_C_COMPILER="..." -DCMAKE_CXX_COMPILER="..."
```

Tools are off because that is broken as well but not critical.

Windows GCC 11.2 is also broken with ADD_DEFINITIONS( -U__STRICT_ANSI__ ) from CMakeLists.txt on my end, but fine without it. I'm not familiar with the macro though so I'm not touching it.

Any feedback on this would have been nice. A working release even more :)
