### ISSUE TITLE
Errors compiling under i686-w64-mingw32-gcc

### ISSUE THREAD

**Issue by outfrost** [assimp/assimp#3353]
The [`mingw-w64-assimp`](https://aur.archlinux.org/packages/mingw-w64-assimp/) [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-assimp&id=6c98adcfeff816f9bd3350d7af81d60ecf7ed28d) in the AUR builds both a 64-bit and a 32-bit version of the assimp library. When I replaced the 5.0.1 release sources with current master (ac8a8a5ad433afd2a10124774685f9db1edbe701) to retest for #3252, I got compilation errors.

Host | Target | Toolchain | Result
---|---|---|---
Linux x86-64 | Linux x86-64 | Native | ✅ OK
Linux x86-64 | Windows x86-64 | `x86_64-w64-mingw32-*` | ✅ OK
Linux x86-64 | Windows i686 | `i686-w64-mingw32-*` | ❌ Fail

**To Reproduce**
```sh
git clone https://github.com/assimp/assimp.git
cd assimp
i686-w64-mingw32-cmake -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DASSIMP_ENABLE_BOOST_WORKAROUND=OFF CMakeLists.txt
make
```

This produces the error:

```
[  8%] Building CXX object code/CMakeFiles/assimp.dir/Common/StandardShapes.cpp.obj
/home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/Common/DefaultIOStream.cpp:72:5: error: ‘int {anonymous}::select_fseek(FILE*, int64_t, int) [with unsigned int sizeOfPointer = 8]’ defined but not used [-Werror=unused-function]
   72 | int select_fseek<8>(FILE *file, int64_t offset, int origin) {
      |     ^~~~~~~~~~~~~~~
/home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/Common/DefaultIOStream.cpp:67:8: error: ‘size_t {anonymous}::select_ftell(FILE*) [with unsigned int sizeOfPointer = 8]’ defined but not used [-Werror=unused-function]
   67 | size_t select_ftell<8>(FILE *file) {
      |        ^~~~~~~~~~~~~~~
```

Configuring with
```sh
i686-w64-mingw32-cmake -DCMAKE_CXX_FLAGS='-Wno-error=unused-function' -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF -DASSIMP_ENABLE_BOOST_WORKAROUND=OFF CMakeLists.txt
```

Produces the following error:

```
[ 27%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/GenBoundingBoxesProcess.cpp.obj
/home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/PostProcessing/TriangulateProcess.cpp: In member function ‘bool Assimp::TriangulateProcess::TriangulateMesh(aiMesh*)’:
/home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/PostProcessing/TriangulateProcess.cpp:198:50: error: argument 1 value ‘4294967294’ exceeds maximum object size 2147483647 [-Werror=alloc-size-larger-than=]
  198 |     std::unique_ptr<bool[]> done(new bool[max_out]);
      |                                                  ^
In file included from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/include/assimp/types.h:77,
                 from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/include/assimp/Importer.hpp:60,
                 from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/include/assimp/GenericProperty.h:52,
                 from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/Common/BaseProcess.h:46,
                 from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/PostProcessing/TriangulateProcess.h:49,
                 from /home/outfrost/AUR/mingw-w64-assimp/src/assimp-5.0.1/code/PostProcessing/TriangulateProcess.cpp:62:
/usr/i686-w64-mingw32/include/c++/10.1.0/new:128:26: note: in a call to allocation function ‘void* operator new [](std::size_t)’ declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^~~~~~~~
```

This is reproducible on master as of ac8a8a5ad433afd2a10124774685f9db1edbe701.

**Desktop**
 - OS: Manjaro

**Additional context**
- Compiler: `i686-w64-mingw32-gcc (GCC) 10.1.0`
- Toolchain:
    [`mingw-w64-binutils-bin`](https://aur.archlinux.org/packages/mingw-w64-binutils-bin/) 2.34-2
    [`mingw-w64-crt-bin`](https://aur.archlinux.org/packages/mingw-w64-crt-bin/) 7.0.0-2
    [`mingw-w64-gcc-bin`](https://aur.archlinux.org/packages/mingw-w64-gcc-bin/) 10.1.0-1
    [`mingw-w64-headers-bin`](https://aur.archlinux.org/packages/mingw-w64-headers-bin/) 7.0.0-1
    [`mingw-w64-winpthreads-bin`](https://aur.archlinux.org/packages/mingw-w64-winpthreads-bin/) 7.0.0-2
* CMake: [`mingw-w64-cmake`](https://aur.archlinux.org/packages/mingw-w64-cmake/) 1-34

**Comment by kimkulling** [comment]
Thanks for your report. There was a inconsistency in the compiler-specific definition of local helper functions. PR is in the pipeline.

**Comment by kimkulling** [comment]
Hopefully the last error shall be fixed now.

**Comment by outfrost** [comment]
It does indeed seem resolved. Thank you!

**Comment by kimkulling** [comment]
I am really really really happy to hear that :-) ! You are welcome.

**Comment by ffontaine** [comment]
We have the same error since we bumped our version of assimp to 5.1.0 in buildoot. This error is raised, at least, with uclibc and glibc toolchains and gcc 9.3.0:

```
/home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/code/PostProcessing/TriangulateProcess.cpp: In member function 'bool Assimp::TriangulateProcess::TriangulateMesh(aiMesh*)':
/home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/code/PostProcessing/TriangulateProcess.cpp:285:50: error: argument 1 value '4294967294' exceeds maximum object size 2147483647 [-Werror=alloc-size-larger-than=]
  285 |     std::unique_ptr<bool[]> done(new bool[max_out]);
      |                                                  ^
In file included from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/include/assimp/types.h:77,
                 from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/include/assimp/Importer.hpp:60,
                 from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/include/assimp/GenericProperty.h:52,
                 from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/code/Common/BaseProcess.h:46,
                 from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/code/PostProcessing/TriangulateProcess.h:49,
                 from /home/buildroot/autobuild/instance-2/output-1/build/assimp-5.1.0/code/PostProcessing/TriangulateProcess.cpp:62:
/home/buildroot/autobuild/instance-2/output-1/host/opt/ext-toolchain/nios2-buildroot-linux-gnu/include/c++/9.3.0/new:127:26: note: in a call to allocation function 'void* operator new [](std::size_t)' declared here
  127 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^~~~~~~~
```

Full build log: http://autobuild.buildroot.org/results/c6e/c6e703bc367c58853005a2f0410354c55d6366b8/build-end.log

I don't know how to properly fix this error. However, I would advise to revert c31e49198adfe2cff7dd12591c0378c7434b5178 to allow downstream projects to disable `-Werror`.

**Comment by SupervisedThinking** [comment]
I'm having the same problem on ARM builds using https://github.com/assimp/assimp/releases/tag/v5.2.1 :

```
UNPACK      assimp
BUILD      assimp (target)
    TOOLCHAIN      cmake (auto-detect)
Executing (target): cmake -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE=/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/etc/cmake-armv8a-libreelec-linux-gnueabihf.conf -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DASSIMP_BUILD_TESTS=OFF /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabihf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabihf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared libraries enabled
-- Looking for ZLIB...
-- Found PkgConfig: /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/armv8a-libreelec-linux-gnueabihf/sysroot/usr/lib/libz.so;debug;/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/armv8a-libreelec-linux-gnueabihf/sysroot/usr/lib/libz.so
-- Checking for module 'minizip'
--   No package 'minizip' found
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
-- Disabled exporter formats:
-- Configuring done
-- Generating done
-- Build files have been written to: /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/.armv8a-libreelec-linux-gnueabihf
Executing (target): ninja 
[70/233] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/TriangulateProcess.cpp.o
FAILED: code/CMakeFiles/assimp.dir/PostProcessing/TriangulateProcess.cpp.o 
/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/bin/armv8a-libreelec-linux-gnueabihf-g++ -DASSIMP_BUILD_DLL_EXPORT -DASSIMP_BUILD_NO_C4D_IMPORTER -DASSIMP_BUILD_NO_M3D_EXPORTER -DASSIMP_BUILD_NO_M3D_IMPORTER -DASSIMP_BUILD_NO_OWN_ZLIB -DASSIMP_IMPORTER_GLTF_USE_OPEN3DGC=1 -DMINIZ_USE_UNALIGNED_LOADS_AND_STORES=0 -DOPENDDLPARSER_BUILD -DRAPIDJSON_HAS_STDSTRING=1 -DRAPIDJSON_NOMEMBERITERATORCLASS -Dassimp_EXPORTS -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/.armv8a-libreelec-linux-gnueabihf/include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/.armv8a-libreelec-linux-gnueabihf -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/. -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../contrib/pugixml/src -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../contrib/rapidjson/include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../contrib -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../contrib/unzip -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../contrib/openddlparser/include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/../include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/.armv8a-libreelec-linux-gnueabihf/code/../include -I/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/.. -fvisibility=hidden -fno-strict-aliasing -Wall -march=armv8-a+crc -mtune=cortex-a53 -mabi=aapcs-linux -Wno-psabi -Wa,-mno-warn-deprecated -mfloat-abi=hard -mfpu=neon-fp-armv8 -Wall -pipe  -O2 -fomit-frame-pointer -DNDEBUG -O3 -DNDEBUG -fPIC -Werror -std=gnu++11 -MD -MT code/CMakeFiles/assimp.dir/PostProcessing/TriangulateProcess.cpp.o -MF code/CMakeFiles/assimp.dir/PostProcessing/TriangulateProcess.cpp.o.d -o code/CMakeFiles/assimp.dir/PostProcessing/TriangulateProcess.cpp.o -c /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/PostProcessing/TriangulateProcess.cpp
/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/PostProcessing/TriangulateProcess.cpp: In member function 'bool Assimp::TriangulateProcess::TriangulateMesh(aiMesh*)':
/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/PostProcessing/TriangulateProcess.cpp:285:50: error: argument 1 value '4294967294' exceeds maximum object size 2147483647 [-Werror=alloc-size-larger-than=]
  285 |     std::unique_ptr<bool[]> done(new bool[max_out]);
      |                                                  ^
In file included from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/include/assimp/types.h:77,
                 from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/include/assimp/Importer.hpp:60,
                 from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/include/assimp/GenericProperty.h:52,
                 from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/Common/BaseProcess.h:46,
                 from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/PostProcessing/TriangulateProcess.h:49,
                 from /build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/build/assimp-5.2.1/code/PostProcessing/TriangulateProcess.cpp:62:
/build/LibreELEC-RR/build.LibreELEC-AMLGX.arm-11.0-devel/toolchain/armv8a-libreelec-linux-gnueabihf/include/c++/10.3.0/new:128:26: note: in a call to allocation function 'void* operator new [](std::size_t)' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^~~~~~~~
cc1plus: all warnings being treated as errors
[73/233] Building CXX object code/CMakeFiles/assimp.dir/AssetLib/3DS/3DSConverter.cpp.o
ninja: build stopped: subcommand failed.
FAILURE: scripts/build assimp during make_target (default)
*********** FAILED COMMAND ***********
ninja ${NINJA_OPTS} ${PKG_MAKE_OPTS_TARGET}
**************************************
```

**Comment by ffontaine** [comment]
FYI, in buildroot, we had to patch assimp to remove `-Werror`: https://git.buildroot.net/buildroot/tree/package/assimp/0001-code-disable-Werror.patch

Would be great to put back `ASSIMP_WERROR` ...
