### ISSUE TITLE
Error C2220 while compiling stepfile.h with VS2017 Community Edition

### ISSUE THREAD

**Issue by escherstair** [assimp/assimp#2210]
I've just found a bug while trying to compile with VS2017 Community Edition 15.8.9 on my Win7 x64 PC for 32 bit target.
Here the steps to reproduce:

1. download commit [2d74514](https://github.com/assimp/assimp/commit/2d74514eabd0c9bf0ebdb1901b94af59853952da)

2. from the command prompt, launch an _out-of-source build_
```
mkdir build
cd “/path/to/my/build/folder”
cmake “/path/to/my/source/folder” –DASSIMP_WERROR=ON – G “Visual Studio 15 2017”
```
This generates Visual Studio files (solution and project)

3. start VS2017 and build project assimp

The following line
https://github.com/assimp/assimp/blob/2d74514eabd0c9bf0ebdb1901b94af59853952da/code/STEPFile.h#L145
gives the warning
`error C4146: unary minus operator applied to unsigned type, result still unsigned`
and this brings to error
`error C2220: warning treated as error - no 'object' file generated`

I see that this behavior can be avoided removing the [/WX](https://msdn.microsoft.com/en-us/library/ms235592.aspx) switch, but I think it's better to fix the source file.

I see that AppVeyor successfully builds with VS2017 for x86 but I see from the log
```
-- The C compiler identification is MSVC 19.15.26730.0
-- The CXX compiler identification is MSVC 19.15.26730.0

```
In my build I see
```
-- The C compiler identification is MSVC 19.15.26732.1
-- The CXX compiler identification is MSVC 19.15.26732.1

```

Note the minor difference 26732.1 vs 26730.0
I don't know if this can explain the different behavior (success vs failure).

I see that the line in stepfile.h has been added in this commit 931ef2cd0bd104fbbbb3214a9b36758ac288c670

**Comment by escherstair** [comment]
`-1u` seems a trivial definition, but as explained [in this post](http://brnz.org/hbr/?p=1433) it involves a lot of different aspects in the background.

This is the reason why VS2017 adds the warning (I think).

If someone can clarify a little bit what was the original intent for defining `ENTITY_NOT_SPECIFIED_32` as `-1u` I can propose a PR with a patch.
Should it be a 32-bit `unsigned int` with value `0xffffffff`?

**Comment by kimkulling** [comment]
Thanks for the hint, typo from my side. Working twith the generated code from the stepfile is a little bit tricky.

**Comment by escherstair** [comment]
Do you mean you're going to fix the bug by yourself?
Thanks
