### ISSUE TITLE
master does not build on clang-7.0.1

### ISSUE THREAD

**Issue by lerppana** [assimp/assimp#2327]
Master does not currently build on my build machine:
macos 10.14.3
Clang 7.0.1

seems to be a problem with gltf2importer and rapidjson:
```
In file included from .../assimp/code/glTF2Importer.cpp:61:
In file included from .../assimp/code/glTF2Asset.h:64:
.../assimp/code/../contrib/rapidjson/include/rapidjson/document.h:1314:22: error: call to constructor of 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is ambiguous
        GenericValue v(value);
                     ^ ~~~~~
.../assimp/code/../contrib/rapidjson/include/rapidjson/document.h:1385:16: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
.../assimp/code/glTF2AssetWriter.inl:100:13: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
        obj.AddMember("byteOffset", a.byteOffset, w.mAl);
            ^
... other stuff
```

**Comment by kimkulling** [comment]
Closed by https://github.com/assimp/assimp/pull/2328
