### ISSUE TITLE
Bug: ai_real is not declared in quaternions.h when _cplusplus is not defined

### ISSUE THREAD

**Issue by AliceRixte** [assimp/assimp#5979]
**Describe the bug**

I'm currently updating an old binding of assimp in Haskell (see  [assimp](https://github.com/joelburget/assimp) ). I managed to make the binding work with version 5.3.1.

However I have to change one line in `quaternions.h`, because the clang compiler embedded in Haskell's compiler fails to compile.  

**To Reproduce**
On windows : 

1. Install assimp using MSys2 via the command ` pacman -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-assimp`
2. Try to build   [assimp](https://github.com/joelburget/assimp) using `cabal build`
3. This will yield the following error

```
quaternion.h:139:5: error: unknown type name 'ai_real'
assimp      >     ai_real w, x, y, z;
```

**Dirty Fix**
This can be fixed by simply adding  the following at the line 137.

```typedef float ai_real;` ``` 

That's probably a horrible thing to do, but it works.

**Expected behavior**
Assimp compiles properly.

**Platform:**
 - OS: Windows 11

**Comment by turol** [comment]
`ai_real` is defined in `defs.h` which is included by `quaternion.h`. There's something wrong with your compiler or preprocessor.

**Comment by AliceRixte** [comment]
Yes this is what I saw and I am surprised too. I'm going to try to raise an issue to GHC, see if it's in cause.

**Comment by kimkulling** [comment]
You need to generate the config.h I guess. This will be done by the cmake run.
