### ISSUE TITLE
Bug: Build does not work on WSL2 Ubuntu 20.04 with g++

### ISSUE THREAD

**Issue by kimkulling** [assimp/assimp#4407]
**Describe the bug**
```
In file included from /home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Importer.cpp:46:
/home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Asset.h: In constructor ‘glTF2::Asset::Asset(Assimp::IOSystem*, rapidjson::IRemoteSchemaDocumentProvider*)’:
/home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Asset.h:1217:47: error: ‘glTF2::Asset::mSchemaDocumentProvider’ will be initialized after [-Werror=reorder]
 1217 |     rapidjson::IRemoteSchemaDocumentProvider *mSchemaDocumentProvider;
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~
/home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Asset.h:1142:24: error:   ‘glTF2::LazyDict<glTF2::Accessor> glTF2::Asset::accessors’ [-Werror=reorder]
 1142 |     LazyDict<Accessor> accessors;
      |                        ^~~~~~~~~
/home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Asset.h:1160:5: error:   when initialized here [-Werror=reorder]
 1160 |     Asset(IOSystem *io = nullptr, rapidjson::IRemoteSchemaDocumentProvider *schemaDocumentProvider = nullptr) :
      |     ^~~~~
/home/kimkulling/10_project/assimp/code/AssetLib/glTF2/glTF2Asset.h:1160:5: error: multiple initializations given for ‘glTF2::Asset::accessors’
cc1plus: all warnings being treated as errors
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:2364: code/CMakeFiles/assimp.dir/AssetLib/glTF2/glTF2Importer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:232: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
kimkulling@DESKTOP-TR1F7QU:~/10_project/assimp$ code .
kimkulling@DESKTOP-TR1F7QU:~/10_project/assimp$ make
[  5%] Built target zlibstatic

```

**To Reproduce**
Try to build with gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Steps to reproduce the behavior:**
Just build it

**Expected behavior**
Clean build

**Platform (please complete the following information):**
 - OS: Linux Ubuntu 20.04
