### ISSUE TITLE
Cannot compile with emscripten 1.37.9 on OSX Sierra 10.12.6

### ISSUE THREAD

**Issue by zacharycarter** [assimp/assimp#1455]
I generate makefiles like so -
```
cmake -DEMSCRIPTEN=1 -DCMAKE_CXX_COMPILER=em++ -DCMAKE_C_COMPILER=emcc -DCMAKE_TOOLCHAIN_FILE=/Users/zachcarter/projects/emsdk/emscripten/1.37.9/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_MODULE_PATH=/Users/zachcarter/projects/emsdk/emscripten/1.37.9/cmake -DASSIMP_ENABLE_BOOST_WORKAROUND=1 -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
```

And here are the errors I encounter:
```
/Users/zachcarter/projects/assimp/code/Q3BSPZipArchive.cpp:139:16: error: use of undeclared identifier 'malloc'
    m_Buffer = malloc(m_Size);
               ^
/Users/zachcarter/projects/assimp/code/Q3BSPZipArchive.cpp:143:5: error: use of undeclared identifier 'free'
    free(m_Buffer);
```
