### ISSUE TITLE
Microsoft Visual Studio 2017 Building Issue C2678 / C2088

### ISSUE THREAD

**Issue by rathaROG** [assimp/assimp#1548]
Hello! I've got this problem while building with Visual Studio 2017 on Windows 10 64-bit.

`3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\include\algorithm(909): error C2678: binary '!=': no operator found which takes a left-hand operand of type 'Assimp::WordIterator' (or there is no acceptable conversion) (compiling source file D:\DEVLibs\assimp\v401\code\X3DImporter.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\include\algorithm(909): error C2088: '!=': illegal for struct`

How should I fix this? Please help me!

**Comment by tomvierjahn** [comment]
We are experiencing the very same errors using Microsoft Visual Studio 2017 Version 15.0.26730.12 on windows. However, it builds fine on Linux (centos 7 with gcc5.3.1 and gcc6.3.1) and MacOs X using apple-clang 9.

**Comment by rathaROG** [comment]
Thank you so much for your confirm! Looks like it is a bug in the compiler generated assignment operator of Microsoft Visual Studio 2017.

**Comment by kimkulling** [comment]
I will try to reproduce it.

**Comment by rathaROG** [comment]
That would be great! Thank you so much for that! :)

**Comment by rythmiq** [comment]
I believe someone has already fixed this on master. Operator (==, !=) parameters in release builds (4.0.x) are not passed as const references. [Commit](https://github.com/assimp/assimp/commit/b26fea4cf5b908bba03e026b358a1778559c1dc8) that fixed it.

**Comment by tomvierjahn** [comment]
Tested it with 9756b48. Works.

**Comment by rathaROG** [comment]
I will try later. Thank you guys so much!

**Comment by Marnoximo** [comment]
9756b48 also worked for me, thanks a lot!
